[package]
name = "animals"
version = "0.0.0"
authors = ["Jordan Last <jordan.michael.last@gmail.com>"]
edition = "2018"

[lib]
path = "src/animals.rs"
crate-type = ["cdylib"]

[dependencies]
ic-cdk = "=0.1.0"
ic-cdk-macros = "=0.1.0"
candid = "=0.6.7"
juniper = "=0.15.10"
serde_json = "=1.0.58"